securesign/trillian

README.md, redhat/release/update-to-head.sh
Made the additions suggested in issue #3 .
Fixes: https://github.com/securesign/trillian/issues/3
=> Update script changes

redhat/release/update-to-head.sh
Just fixing small small text errors and chnaging references to main branch to master as trillian is operating off of a master branch.
=> Small Adjustments

redhat/overlays/trillian_db/Dockerfile.database, redhat/release/update-to-head.sh
Contains the following.
- New Dockerfile needed for Building the Database Image.
- Updates to the update-to-head script.
=> Trillian rhtap config

redhat/release/update-to-head.sh
Update for the update to head script to git mv the files so they will actually get moved to their new branches.
=> Adding the git mv commands to master

redhat/release/update-to-head.sh
Getting the update to head script to be inline with those in the other securesign repos.
=> Script update

redhat/overlays/60-load-db.sh, redhat/overlays/Dockerfile.database, redhat/release/update-to-head.sh
Adding the load db script for the database image build.
=> Trillian rhtap changes

redhat/release/update-to-head.sh
Fixes https://issues.redhat.com/browse/SECURESIGN-104
=> chore: don't force push the release branch

.tekton/trillian-database-pull-request.yaml, .tekton/trillian-database-push.yaml, .tekton/trillian-logserver-pull-request.yaml, .tekton/trillian-logserver-push.yaml, .tekton/trillian-logsigner-pull-request.yaml, .tekton/trillian-logsigner-push.yaml, .tekton/trillian-netcat-pull-request.yaml, .tekton/trillian-netcat-push.yaml
Some of the changes required for the enterprise contracts. More changes will follow as I make my way through the documentation and test how it works via my fork.
=> Trillian enterprise contracts

redhat/overlays/Dockerfile.database, redhat/overlays/Dockerfile.logserver, redhat/overlays/Dockerfile.logsigner, redhat/overlays/Dockerfile.netcat
=> chore: Adds new com.redhat.component label

.tekton/trillian-netcat-pull-request.yaml, .tekton/trillian-netcat-push.yaml, Dockerfile.netcat
Decided to have this ready for when we need to rename our EC tests.
=> Removing NetCat Hermetic Build

.tekton/trillian-database-pull-request.yaml, .tekton/trillian-database-push.yaml, .tekton/trillian-logserver-pull-request.yaml, .tekton/trillian-logserver-push.yaml, .tekton/trillian-logsigner-pull-request.yaml, .tekton/trillian-logsigner-push.yaml, .tekton/trillian-netcat-pull-request.yaml, .tekton/trillian-netcat-push.yaml
Adds source images for each pipeline to satisfy legal requirements.
=> pipelines: add source image builds to all pipelines

.tekton/trillian-database-1-5-pull-request.yaml, .tekton/trillian-database-1-5-push.yaml, .tekton/trillian-logserver-1-5-pull-request.yaml, .tekton/trillian-logserver-1-5-push.yaml, .tekton/trillian-logsigner-1-5-pull-request.yaml, .tekton/trillian-logsigner-1-5-push.yaml, .tekton/trillian-netcat-1-5-pull-request.yaml, .tekton/trillian-netcat-1-5-push.yaml
/cc @lance @tommyd450 
based on #79, thanks for your work on this Tommy.
=> optimizing build conditions to reduce RHTAP workloads

.tekton/trillian-database-1-5-pull-request.yaml, .tekton/trillian-database-1-5-push.yaml, .tekton/trillian-logserver-1-5-pull-request.yaml, .tekton/trillian-logserver-1-5-push.yaml, .tekton/trillian-logsigner-1-5-pull-request.yaml, .tekton/trillian-logsigner-1-5-push.yaml, .tekton/trillian-netcat-1-5-pull-request.yaml, .tekton/trillian-netcat-1-5-push.yaml, .tekton/trillian-unit-test.yaml
PR to add go unit tests to trillian
=> SECURESIGN-185 | Add tests to all pipelines

.tekton/trillian-database-1-5-push.yaml, .tekton/trillian-logserver-1-5-push.yaml, .tekton/trillian-logsigner-1-5-push.yaml, .tekton/trillian-netcat-1-5-push.yaml
remove the cel expressions in the push pipelines so that they always run on any push to the release branch.
=> fix: remove the cel expressions in the push pipelines

.tekton/trillian-database-1-5-push.yaml, .tekton/trillian-logserver-1-5-push.yaml, .tekton/trillian-logsigner-1-5-push.yaml, .tekton/trillian-netcat-1-5-push.yaml
=> Remove cel expression

release-plans/gamma/ReleasePlan.yaml
=> adding release plan for gamma

Dockerfile.logsigner.rh
generate a new build for log signer
=> generate build for logsigner

.github/workflows/trigger-konflux-build.yaml, .tekton/database-pull-request.yaml, .tekton/logserver-pull-request.yaml, .tekton/logsigner-pull-request.yaml
Adding this action: https://github.com/securesign/actions/blob/main/.github/workflows/trigger-konflux-build.yaml
=> add-tigger-action

Dockerfile.redis.rh
downgrade-redis-version to get it to build
=> downgrade-redis-version

.tekton/createtree-pull-request.yaml, .tekton/createtree-push.yaml, .tekton/updatetree-pull-request.yaml, .tekton/updatetree-push.yaml
This change configures prefetched dependencies and hermetic builds for createtree and updatetree builds.
=> chore: prefetch dependencies and hermetic builds
